"use client";

import { useEffect, useRef } from "react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { CobwebCorner } from "./CobwebDecoration";

gsap.registerPlugin(ScrollTrigger);

const FAQ_ITEMS = [
  // Ingresos y propiedad (ajustados según correcciones_tubi.md)
  {
    q: "How does the payment model work?",
    a: "We operate on a Revenue-Share model. You earn a share of the net revenue generated by the ads shown on your content. Payments are issued monthly.",
  },
  {
    q: "Do I lose ownership of my content?",
    a: "No. You remain the 100% owner of your content and Intellectual Property (IP). You grant us a license solely to distribute and monetize your videos on Tubi.",
  },
  // Tipo de contenido y aplicación (nuevas preguntas del doc)
  {
    q: "Can I upload any type of video?",
    a: "Tubi is a premium platform for movies and TV shows. We are specifically looking for narrative, scripted, or documentary-style content that feels like TV. Vlogs, gaming let's plays, or short clips are generally not a fit.",
  },
  {
    q: "Why do I need to apply?",
    a: "This is an Invite-Only opportunity. Tubi maintains high quality standards, so every creator and video series must undergo a moderation and approval process before being distributed.",
  },
  // Preguntas adicionales originales que siguen siendo válidas
  {
    q: "Is there a minimum payout?",
    a: "Yes. There is a minimum threshold of $250 USD. If you earn less than that in a month, the balance rolls over to the next payment cycle.",
  },
  {
    q: "Will my full video library be uploaded?",
    a: "The plan is to distribute your channel's long-form content library. Each file should be at least 15 minutes in duration. Compilations of shorter episodes are ideal for meeting this requirement.",
  },
  {
    q: "Are there content restrictions?",
    a: "Tubi accepts most approved themes, including mature or sensitive topics. Political content is not allowed. All content must comply with Tubi's suitability guidelines and must be free of burnt-in ads, watermarks, or lower-thirds.",
  },
  {
    q: "Will my original titles and thumbnails be kept?",
    a: "Your video titles remain unchanged. Thumbnails may be adapted by the team to meet Tubi's technical and visual specifications.",
  },
  {
    q: "Will Tubi promote my content?",
    a: "Creator content can be featured in dedicated sections like Creatorverse and placed on relevant shelves so fans of the genre can discover your work more easily.",
  },
];

interface FAQSectionTubiProps {
  onTryIt: () => void;
}

export function FAQSectionTubi({ onTryIt }: FAQSectionTubiProps) {
  const sectionRef = useRef<HTMLElement>(null);
  const titleRef = useRef<HTMLHeadingElement>(null);
  const accordionRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const ctx = gsap.context(() => {
      gsap.fromTo(titleRef.current, { opacity: 0, y: 40 }, { opacity: 1, y: 0, duration: 0.8, scrollTrigger: { trigger: sectionRef.current, start: "top 80%", toggleActions: "play none none reverse" } });
      gsap.fromTo(accordionRef.current, { opacity: 0, y: 30 }, { opacity: 1, y: 0, duration: 0.6, scrollTrigger: { trigger: accordionRef.current, start: "top 85%", toggleActions: "play none none reverse" } });
    }, sectionRef);
    return () => ctx.revert();
  }, []);

  return (
    <section
      ref={sectionRef}
      id="faq"
      className="relative scroll-mt-20 bg-tubi-dark py-24"
    >
      <CobwebCorner position="top-left" />
      <CobwebCorner position="bottom-right" />
      <div className="container relative mx-auto max-w-3xl px-6">
        <h2 ref={titleRef} className="mb-4 text-center text-3xl font-bold text-tubi-yellow sm:text-4xl md:text-[2.5rem]">
          Frequently Asked Questions
        </h2>
        <p className="mb-12 text-center text-lg text-tubi-yellow/80 md:text-xl">
          Everything you need to know about distributing on Tubi
        </p>

        <div ref={accordionRef}>
          <Accordion type="single" collapsible className="w-full space-y-3">
            {FAQ_ITEMS.map((item, i) => (
              <AccordionItem
                key={i}
                value={`tubi-faq-${i}`}
                className="overflow-hidden rounded-xl border border-tubi-yellow/20 bg-tubi-purple/10 px-4 transition-colors hover:border-tubi-yellow/30 data-[state=open]:border-tubi-yellow/40"
              >
                <AccordionTrigger className="py-5 text-left text-base font-medium text-tubi-yellow hover:no-underline hover:text-white md:text-lg">
                  {item.q}
                </AccordionTrigger>
                <AccordionContent className="pb-5 text-base text-tubi-yellow/90 md:text-lg">
                  {item.a}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>

        <div className="mt-16 flex flex-col items-center gap-6 rounded-2xl border border-tubi-yellow/20 bg-tubi-purple/10 p-8 text-center">
          <p className="text-xl font-semibold text-tubi-yellow md:text-2xl">
            Ready to expand beyond YouTube?
          </p>
          <Button
            size="lg"
            onClick={onTryIt}
            className="cursor-pointer bg-tubi-yellow px-8 py-6 text-lg font-semibold text-tubi-dark hover:bg-tubi-dark hover:text-tubi-yellow"
          >
            Apply for Access
          </Button>
        </div>
      </div>
    </section>
  );
}
